import { type NextPage } from "next"
import Head from "next/head"
import Image from 'next/image'
import * as RadioGroup from '@radix-ui/react-radio-group'

// bg is verydarkblue for sure
//
const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Interactive rating component</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-verydarkblue h-screen w-full flex justify-center items-center">
        <section>
          <RatingCard />
        </section>
      </main>
    </>
  );
};

export default Home;


const RatingCard = () => {
  return (
    <form className="bg-darkerblue rounded-xl p-9 text-lightgrey w-[415px] h-[415px] flex flex-col justify-between">
      <figure className="bg-darkblue rounded-full p-0 w-10 h-10 flex justify-center items-center">
        <Image src="images/icon-star.svg" alt="" width={15} height={15} className="w-auto h-auto" />
      </figure>
      <h1 className="text-white text-xl">How did we do?</h1>
      <p>
        Please let us know how we did with your support request. All feedback is appreciated
        to help us improve our offering!
      </p>

      <RadioGroup.Root className="flex justify-between i">
        {["1", "2", "3", "4", "5"].map(n => (
          <RadioGroup.Item key={n} value={n} id={`r${n}`} className="bg-darkblue rounded-full w-12 h-12 hover:bg-lightgrey hover:text-white checked:bg-primary checked:text-white transition-colors">
            <label htmlFor={`r${n}`}>{n}</label>
          </RadioGroup.Item>
        ))}
      </RadioGroup.Root>
      <button className="uppercase bg-primary text-white w-full rounded-full h-11 hover:bg-white hover:text-primary transition-colors">
        Submit
      </button>
    </form>
  )
}