import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Interactive rating component</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section>
          <RatingCard />
        </section>
      </main>
    </>
  );
};

export default Home;


const RatingCard = () => {
  return (

    <form>
      <h1>How did we do?</h1>
      <p>
        Please let us know how we did with your support request. All feedback is appreciated
        to help us improve our offering!
      </p>

      1 2 3 4 5
      <input type="submit" value="Submit"/>
    </form>
  )
}